function GetCrawlLoot(characterLevel) {
    const randomEquipment = GetRandomEquipment();
    const randomSpell = GetRandomSpell(characterLevel);

    return {
        equipment: randomEquipment,
        spell: randomSpell
    };
}

function GetRandomEquipment(){
    const randomIndex = Math.floor(Math.random() * equipments.length);
    return equipments[randomIndex];
}
function GetRandomSpell(characterLevel) {
    const filteredSpells = spells.filter(spell => spell.characterLevel <= characterLevel);
    if (filteredSpells.length === 0) {
        return null; // No spells found for the given character level or lower
    }
    const randomIndex = Math.floor(Math.random() * filteredSpells.length);
    return filteredSpells[randomIndex];
}



function Spell(spellName, spellLevel, characterLevel) {
    this.spellName = spellName;
    this.spellLevel = spellLevel;
    this.characterLevel = characterLevel;
}

function Equipment(EquipmentName, damage, notes) {
	this.EquipmentName = EquipmentName;
	this.damage =damage;
	this.notes = notes;
}

const equipments = [
	new Equipment("Club","1d4 bludgeoning","Light"),
	new Equipment("Dagger","1d4 piercing","Finesse, light, thrown (range 20/60)"),
	new Equipment("Greatclub","1d8 bludgeoning","Two-handed"),
	new Equipment("Handaxe","1d6 slashing","Light, thrown (range 20/60)"),
	new Equipment("Javelin","1d6 piercing","Thrown (range 30/120)"),
	new Equipment("Light hammer","1d4 bludgeoning","Light, thrown (range 20/60)"),
	new Equipment("Mace","1d6 bludgeoning","—"),
	new Equipment("Quarterstaff","1d6 bludgeoning","Versatile (1d8)"),
	new Equipment("Sickle","1d4 slashing","Light"),
	new Equipment("Spear","1d6 piercing","Thrown (range 20/60), versatile (1d8)"),
	new Equipment("Crossbow, light","1d8 piercing","Ammunition (range 80/320), loading, two-handed"),
	new Equipment("Dart","1d4 piercing","Finesse, thrown (range 20/60)"),
	new Equipment("Shortbow","1d6 piercing","Ammunition (range 80/320), two-handed"),
	new Equipment("Sling","1d4 bludgeoning","Ammunition (range 30/120)"),
	new Equipment("Battleaxe","1d8 slashing","Versatile (1d10)"),
	new Equipment("Flail","1d8 bludgeoning","—"),
	new Equipment("Glaive","1d10 slashing","Heavy, reach, two-handed"),
	new Equipment("Greataxe","1d12 slashing","Heavy, two-handed"),
	new Equipment("Greatsword","2d6 slashing","Heavy, two-handed"),
	new Equipment("Halberd","1d10 slashing","Heavy, reach, two-handed"),
	new Equipment("Lance","1d12 piercing","Reach, special"),
	new Equipment("Longsword","1d8 slashing","Versatile (1d10)"),
	new Equipment("Maul","2d6 bludgeoning","Heavy, two-handed"),
	new Equipment("Morningstar","1d8 piercing","—"),
	new Equipment("Pike","1d10 piercing","Heavy, reach, two-handed"),
	new Equipment("Rapier","1d8 piercing","Finesse"),
	new Equipment("Scimitar","1d6 slashing","Finesse, light"),
	new Equipment("Shortsword","1d6 piercing","Finesse, light"),
	new Equipment("Trident","1d6 piercing","Thrown (range 20/60), versatile (1d8)"),
	new Equipment("War pick","1d8 piercing","—"),
	new Equipment("Warhammer","1d8 bludgeoning","Versatile (1d10)"),
	new Equipment("Whip","1d4 slashing","Finesse, reach"),
	new Equipment("Blowgun","1 piercing","Ammunition (range 25/100), loading"),
	new Equipment("Crossbow, hand","1d6 piercing","Ammunition (range 30/120), light, loading"),
	new Equipment("Crossbow, heavy","1d10 piercing","Ammunition (range 100/400), heavy, loading, two-handed"),
	new Equipment("Longbow","1d8 piercing","Ammunition (range 150/600), heavy, two-handed"),
	new Equipment("Net","0","Special, thrown (range 5/15)"),
	new Equipment("Padded","0","Light,AC = 11 + Dex modifier,Stealth Disadvantage"),
	new Equipment("Leather","0","Light,AC = 11 + Dex modifier"),
	new Equipment("Studded leather","0","Light,AC = 12 + Dex modifier"),
	new Equipment("Hide","0","Medium,AC = 12 + Dex modifier (max 2)"),
	new Equipment("Chain shirt","0","Medium,AC = 13 + Dex modifier (max 2)"),
	new Equipment("Scale mail","0","Medium,AC = 14 + Dex modifier (max 2),Stealth Disadvantage"),
	new Equipment("Breastplate","0","Medium,AC = 14 + Dex modifier (max 2)"),
	new Equipment("Half plate","0","Medium,AC = 15 + Dex modifier (max 2),Stealth Disadvantage"),
	new Equipment("Ring mail","0","Heavy,AC = 14,Stealth Disadvantage"),
	new Equipment("Chain mail","0","Heavy,AC = 16,Str 13,Stealth Disadvantage"),
	new Equipment("Splint","0","Heavy,AC = 17,Str 15,Stealth Disadvantage"),
	new Equipment("Plate","0","Heavy,AC = 18,Str 15,Stealth Disadvantage"),
	new Equipment("Shield","0","Shield,+2 AC"),
];

const spells = [
	new Spell("AcidSplash",0,1),
	new Spell("ChillTouch",0,1),
	new Spell("DancingLights",0,1),
	new Spell("Druidcraft",0,1),
	new Spell("EldritchBlast",0,1),
	new Spell("FireBolt",0,1),
	new Spell("Guidance",0,1),
	new Spell("Light",0,1),
	new Spell("MageHand",0,1),
	new Spell("Mending",0,1),
	new Spell("Message",0,1),
	new Spell("MinorIllusion",0,1),
	new Spell("PoisonSpray",0,1),
	new Spell("Prestidigitation",0,1),
	new Spell("ProduceFlame",0,1),
	new Spell("RayofFrost",0,1),
	new Spell("Resistance",0,1),
	new Spell("SacredFlame",0,1),
	new Spell("Shillelagh",0,1),
	new Spell("ShockingGrasp",0,1),
	new Spell("SparetheDying",0,1),
	new Spell("Thaumaturgy",0,1),
	new Spell("TrueStrike",0,1),
	new Spell("ViciousMockery",0,1),
	new Spell("Alarm",1,1),
	new Spell("AnimalFriendship",1,1),
	new Spell("Bane",1,1),
	new Spell("Bless",1,1),
	new Spell("BurningHands",1,1),
	new Spell("CharmPerson",1,1),
	new Spell("ColorSpray",1,1),
	new Spell("Command",1,1),
	new Spell("ComprehendLanguages",1,1),
	new Spell("CreateorDestroyWater",1,1),
	new Spell("CureWounds",1,1),
	new Spell("DetectEvilandGood",1,1),
	new Spell("DetectMagic",1,1),
	new Spell("DetectPoisonandDisease",1,1),
	new Spell("DisguiseSelf",1,1),
	new Spell("DivineFavor",1,1),
	new Spell("Entangle",1,1),
	new Spell("ExpeditiousRetreat",1,1),
	new Spell("FaerieFire",1,1),
	new Spell("FalseLife",1,1),
	new Spell("FeatherFall",1,1),
	new Spell("FindFamiliar",1,1),
	new Spell("FloatingDisk",1,1),
	new Spell("FogCloud",1,1),
	new Spell("Goodberry",1,1),
	new Spell("Grease",1,1),
	new Spell("GuidingBolt",1,1),
	new Spell("HealingWord",1,1),
	new Spell("HellishRebuke",1,1),
	new Spell("Heroism",1,1),
	new Spell("HideousLaughter",1,1),
	new Spell("Hunter'sMark",1,1),
	new Spell("Identify",1,1),
	new Spell("IllusoryScript",1,1),
	new Spell("InflictWounds",1,1),
	new Spell("Jump",1,1),
	new Spell("Longstrider",1,1),
	new Spell("MageArmor",1,1),
	new Spell("MagicMissile",1,1),
	new Spell("ProtectionfromEvilandGood",1,1),
	new Spell("PurifyFoodandDrink",1,1),
	new Spell("Sanctuary",1,1),
	new Spell("Shield",1,1),
	new Spell("ShieldofFaith",1,1),
	new Spell("SilentImage",1,1),
	new Spell("Sleep",1,1),
	new Spell("SpeakwithAnimals",1,1),
	new Spell("Thunderwave",1,1),
	new Spell("UnseenServant",1,1),
	new Spell("AcidArrow",2,3),
	new Spell("Aid",2,3),
	new Spell("AlterSelf",2,3),
	new Spell("AnimalMessenger",2,3),
	new Spell("ArcaneLock",2,3),
	new Spell("Arcanist'sMagicAura",2,3),
	new Spell("Augury",2,3),
	new Spell("Barkskin",2,3),
	new Spell("Blindness/Deafness",2,3),
	new Spell("Blur",2,3),
	new Spell("BrandingSmite",2,3),
	new Spell("CalmEmotions",2,3),
	new Spell("ContinualFlame",2,3),
	new Spell("Darkness",2,3),
	new Spell("Darkvision",2,3),
	new Spell("DetectThoughts",2,3),
	new Spell("EnhanceAbility",2,3),
	new Spell("Enlarge/Reduce",2,3),
	new Spell("Enthrall",2,3),
	new Spell("FindSteed",2,3),
	new Spell("FindTraps",2,3),
	new Spell("FlameBlade",2,3),
	new Spell("FlamingSphere",2,3),
	new Spell("GentleRepose",2,3),
	new Spell("GustofWind",2,3),
	new Spell("HeatMetal",2,3),
	new Spell("HoldPerson",2,3),
	new Spell("Invisibility",2,3),
	new Spell("Knock",2,3),
	new Spell("LesserRestoration",2,3),
	new Spell("Levitate",2,3),
	new Spell("LocateAnimalsorPlants",2,3),
	new Spell("LocateObject",2,3),
	new Spell("MagicMouth",2,3),
	new Spell("MagicWeapon",2,3),
	new Spell("MirrorImage",2,3),
	new Spell("MistyStep",2,3),
	new Spell("Moonbeam",2,3),
	new Spell("PasswithoutTrace",2,3),
	new Spell("PrayerofHealing",2,3),
	new Spell("ProtectionfromPoison",2,3),
	new Spell("RayofEnfeeblement",2,3),
	new Spell("RopeTrick",2,3),
	new Spell("ScorchingRay",2,3),
	new Spell("SeeInvisibility",2,3),
	new Spell("Shatter",2,3),
	new Spell("Silence",2,3),
	new Spell("SpiderClimb",2,3),
	new Spell("SpikeGrowth",2,3),
	new Spell("SpiritualWeapon",2,3),
	new Spell("Suggestion",2,3),
	new Spell("WardingBond",2,3),
	new Spell("Web",2,3),
	new Spell("ZoneofTruth",2,3),
	new Spell("AnimateDead",3,5),
	new Spell("BeaconofHope",3,5),
	new Spell("BestowCurse",3,5),
	new Spell("Blink",3,5),
	new Spell("CallLightning",3,5),
	new Spell("Clairvoyance",3,5),
	new Spell("ConjureAnimals",3,5),
	new Spell("Counterspell",3,5),
	new Spell("CreateFoodandWater",3,5),
	new Spell("Daylight",3,5),
	new Spell("DispelMagic",3,5),
	new Spell("Fear",3,5),
	new Spell("Fireball",3,5),
	new Spell("Fly",3,5),
	new Spell("GaseousForm",3,5),
	new Spell("GlyphofWarding",3,5),
	new Spell("Haste",3,5),
	new Spell("HypnoticPattern",3,5),
	new Spell("LightningBolt",3,5),
	new Spell("MagicCircle",3,5),
	new Spell("MajorImage",3,5),
	new Spell("MassHealingWord",3,5),
	new Spell("MeldintoStone",3,5),
	new Spell("Nondetection",3,5),
	new Spell("PhantomSteed",3,5),
	new Spell("PlantGrowth",3,5),
	new Spell("ProtectionfromEnergy",3,5),
	new Spell("RemoveCurse",3,5),
	new Spell("Revivify",3,5),
	new Spell("Sending",3,5),
	new Spell("SleetStorm",3,5),
	new Spell("Slow",3,5),
	new Spell("SpeakwithDead",3,5),
	new Spell("SpeakwithPlants",3,5),
	new Spell("SpiritGuardians",3,5),
	new Spell("StinkingCloud",3,5),
	new Spell("TinyHut",3,5),
	new Spell("Tongues",3,5),
	new Spell("VampiricTouch",3,5),
	new Spell("WaterBreathing",3,5),
	new Spell("WaterWalk",3,5),
	new Spell("WindWall",3,5),
	new Spell("ArcaneEye",4,7),
	new Spell("Banishment",4,7),
	new Spell("BlackTentacles",4,7),
	new Spell("Blight",4,7),
	new Spell("Compulsion",4,7),
	new Spell("Confusion",4,7),
	new Spell("ConjureMinorElementals",4,7),
	new Spell("ConjureWoodlandBeings",4,7),
	new Spell("ControlWater",4,7),
	new Spell("DeathWard",4,7),
	new Spell("DimensionDoor",4,7),
	new Spell("Divination",4,7),
	new Spell("DominateBeast",4,7),
	new Spell("Fabricate",4,7),
	new Spell("FaithfulHound",4,7),
	new Spell("FireShield",4,7),
	new Spell("FreedomofMovement",4,7),
	new Spell("GiantInsect",4,7),
	new Spell("GreaterInvisibility",4,7),
	new Spell("GuardianofFaith",4,7),
	new Spell("HallucinatoryTerrain",4,7),
	new Spell("IceStorm",4,7),
	new Spell("LocateCreature",4,7),
	new Spell("PhantasmalKiller",4,7),
	new Spell("Polymorph",4,7),
	new Spell("PrivateSanctum",4,7),
	new Spell("ResilientSphere",4,7),
	new Spell("SecretChest",4,7),
	new Spell("StoneShape",4,7),
	new Spell("Stoneskin",4,7),
	new Spell("WallofFire",4,7),
	new Spell("AnimateObjects",5,9),
	new Spell("AntilifeShell",5,9),
	new Spell("ArcaneHand",5,9),
	new Spell("Awaken",5,9),
	new Spell("Cloudkill",5,9),
	new Spell("Commune",5,9),
	new Spell("CommunewithNature",5,9),
	new Spell("ConeofCold",5,9),
	new Spell("ConjureElemental",5,9),
	new Spell("ContactOtherPlane",5,9),
	new Spell("Contagion",5,9),
	new Spell("Creation",5,9),
	new Spell("DispelEvilandGood",5,9),
	new Spell("DominatePerson",5,9),
	new Spell("Dream",5,9),
	new Spell("FlameStrike",5,9),
	new Spell("Geas",5,9),
	new Spell("GreaterRestoration",5,9),
	new Spell("Hallow",5,9),
	new Spell("HoldMonster",5,9),
	new Spell("InsectPlague",5,9),
	new Spell("LegendLore",5,9),
	new Spell("MassCureWounds",5,9),
	new Spell("Mislead",5,9),
	new Spell("ModifyMemory",5,9),
	new Spell("Passwall",5,9),
	new Spell("PlanarBinding",5,9),
	new Spell("RaiseDead",5,9),
	new Spell("Reincarnate",5,9),
	new Spell("Scrying",5,9),
	new Spell("Seeming",5,9),
	new Spell("Telekinesis",5,9),
	new Spell("TelepathicBond",5,9),
	new Spell("TeleportationCircle",5,9),
	new Spell("TreeStride",5,9),
	new Spell("WallofForce",5,9),
	new Spell("WallofStone",5,9),
	new Spell("BladeBarrier",6,11),
	new Spell("ChainLightning",6,11),
	new Spell("CircleofDeath",6,11),
	new Spell("ConjureFey",6,11),
	new Spell("Contingency",6,11),
	new Spell("CreateUndead",6,11),
	new Spell("Disintegrate",6,11),
	new Spell("Eyebite",6,11),
	new Spell("FindthePath",6,11),
	new Spell("FleshtoStone",6,11),
	new Spell("Forbiddance",6,11),
	new Spell("FreezingSphere",6,11),
	new Spell("GlobeofInvulnerability",6,11),
	new Spell("GuardsandWards",6,11),
	new Spell("Harm",6,11),
	new Spell("Heal",6,11),
	new Spell("Heroes'Feast",6,11),
	new Spell("InstantSummons",6,11),
	new Spell("IrresistibleDance",6,11),
	new Spell("MagicJar",6,11),
	new Spell("MassSuggestion",6,11),
	new Spell("MoveEarth",6,11),
	new Spell("PlanarAlly",6,11),
	new Spell("ProgrammedIllusion",6,11),
	new Spell("Sunbeam",6,11),
	new Spell("TransportviaPlants",6,11),
	new Spell("TrueSeeing",6,11),
	new Spell("WallofIce",6,11),
	new Spell("WallofThorns",6,11),
	new Spell("WindWalk",6,11),
	new Spell("WordofRecall",6,11),
	new Spell("ArcaneSword",7,13),
	new Spell("ConjureCelestial",7,13),
	new Spell("DelayedBlastFireball",7,13),
	new Spell("DivineWord",7,13),
	new Spell("Etherealness",7,13),
	new Spell("FingerofDeath",7,13),
	new Spell("FireStorm",7,13),
	new Spell("Forcecage",7,13),
	new Spell("MagnificentMansion",7,13),
	new Spell("MirageArcane",7,13),
	new Spell("PlaneShift",7,13),
	new Spell("PrismaticSpray",7,13),
	new Spell("ProjectImage",7,13),
	new Spell("Regenerate",7,13),
	new Spell("Resurrection",7,13),
	new Spell("ReverseGravity",7,13),
	new Spell("Sequester",7,13),
	new Spell("Simulacrum",7,13),
	new Spell("Symbol",7,13),
	new Spell("Teleport",7,13),
	new Spell("AnimalShapes",8,15),
	new Spell("AntimagicField",8,15),
	new Spell("Antipathy/Sympathy",8,15),
	new Spell("Clone",8,15),
	new Spell("ControlWeather",8,15),
	new Spell("Demiplane",8,15),
	new Spell("DominateMonster",8,15),
	new Spell("Earthquake",8,15),
	new Spell("Feeblemind",8,15),
	new Spell("Glibness",8,15),
	new Spell("HolyAura",8,15),
	new Spell("IncendiaryCloud",8,15),
	new Spell("Maze",8,15),
	new Spell("MindBlank",8,15),
	new Spell("PowerWordStun",8,15),
	new Spell("Sunburst",8,15),
	new Spell("AstralProjection",9,17),
	new Spell("Foresight",9,17),
	new Spell("Gate",9,17),
	new Spell("Imprisonment",9,17),
	new Spell("MassHeal",9,17),
	new Spell("MeteorSwarm",9,17),
	new Spell("PowerWordKill",9,17),
	new Spell("PrismaticWall",9,17),
	new Spell("Shapechange",9,17),
	new Spell("StormofVengeance",9,17),
	new Spell("TimeStop",9,17),
	new Spell("TruePolymorph",9,17),
	new Spell("TrueResurrection",9,17),
	new Spell("Weird",9,17),
	new Spell("Wish",9,17),
]

