function GetCrawlLoot(characterLevel) {
    const randomEquipment = GetRandomEquipment();
    const randomSpell = GetRandomSpell(characterLevel);

    return {
        equipment: randomEquipment,
        spell: randomSpell
    };
}

function GetRandomEquipment(){
    const randomIndex = Math.floor(Math.random() * equipments.length);
    return equipments[randomIndex];
}
function GetRandomSpell(characterLevel) {
    const filteredSpells = spells.filter(spell => spell.characterLevel <= characterLevel);
    if (filteredSpells.length === 0) {
        return null; // No spells found for the given character level or lower
    }
    const randomIndex = Math.floor(Math.random() * filteredSpells.length);
    return filteredSpells[randomIndex];
}



function Spell(spellName, spellLevel, characterLevel) {
    this.spellName = spellName;
    this.spellLevel = spellLevel;
    this.characterLevel = characterLevel;
}

function Equipment(EquipmentName, damage, notes) {
	this.EquipmentName = EquipmentName;
	this.damage =damage;
	this.notes = notes;
}

const equipments = [
	new Equipment("Club","1d4 bludgeoning","Light"),
	new Equipment("Dagger","1d4 piercing","Finesse, light, thrown (range 20/60)"),
	new Equipment("Greatclub","1d8 bludgeoning","Two-handed"),
	new Equipment("Handaxe","1d6 slashing","Light, thrown (range 20/60)"),
	new Equipment("Javelin","1d6 piercing","Thrown (range 30/120)"),
	new Equipment("Light hammer","1d4 bludgeoning","Light, thrown (range 20/60)"),
	new Equipment("Mace","1d6 bludgeoning","—"),
	new Equipment("Quarterstaff","1d6 bludgeoning","Versatile (1d8)"),
	new Equipment("Sickle","1d4 slashing","Light"),
	new Equipment("Spear","1d6 piercing","Thrown (range 20/60), versatile (1d8)"),
	new Equipment("Crossbow, light","1d8 piercing","Ammunition (range 80/320), loading, two-handed"),
	new Equipment("Dart","1d4 piercing","Finesse, thrown (range 20/60)"),
	new Equipment("Shortbow","1d6 piercing","Ammunition (range 80/320), two-handed"),
	new Equipment("Sling","1d4 bludgeoning","Ammunition (range 30/120)"),
	new Equipment("Battleaxe","1d8 slashing","Versatile (1d10)"),
	new Equipment("Flail","1d8 bludgeoning","—"),
	new Equipment("Glaive","1d10 slashing","Heavy, reach, two-handed"),
	new Equipment("Greataxe","1d12 slashing","Heavy, two-handed"),
	new Equipment("Greatsword","2d6 slashing","Heavy, two-handed"),
	new Equipment("Halberd","1d10 slashing","Heavy, reach, two-handed"),
	new Equipment("Lance","1d12 piercing","Reach, special"),
	new Equipment("Longsword","1d8 slashing","Versatile (1d10)"),
	new Equipment("Maul","2d6 bludgeoning","Heavy, two-handed"),
	new Equipment("Morningstar","1d8 piercing","—"),
	new Equipment("Pike","1d10 piercing","Heavy, reach, two-handed"),
	new Equipment("Rapier","1d8 piercing","Finesse"),
	new Equipment("Scimitar","1d6 slashing","Finesse, light"),
	new Equipment("Shortsword","1d6 piercing","Finesse, light"),
	new Equipment("Trident","1d6 piercing","Thrown (range 20/60), versatile (1d8)"),
	new Equipment("War pick","1d8 piercing","—"),
	new Equipment("Warhammer","1d8 bludgeoning","Versatile (1d10)"),
	new Equipment("Whip","1d4 slashing","Finesse, reach"),
	new Equipment("Blowgun","1 piercing","Ammunition (range 25/100), loading"),
	new Equipment("Crossbow, hand","1d6 piercing","Ammunition (range 30/120), light, loading"),
	new Equipment("Crossbow, heavy","1d10 piercing","Ammunition (range 100/400), heavy, loading, two-handed"),
	new Equipment("Longbow","1d8 piercing","Ammunition (range 150/600), heavy, two-handed"),
	new Equipment("Net","0","Special, thrown (range 5/15)"),
	new Equipment("Padded","0","Light,AC = 11 + Dex modifier,Stealth Disadvantage"),
	new Equipment("Leather","0","Light,AC = 11 + Dex modifier"),
	new Equipment("Studded leather","0","Light,AC = 12 + Dex modifier"),
	new Equipment("Hide","0","Medium,AC = 12 + Dex modifier (max 2)"),
	new Equipment("Chain shirt","0","Medium,AC = 13 + Dex modifier (max 2)"),
	new Equipment("Scale mail","0","Medium,AC = 14 + Dex modifier (max 2),Stealth Disadvantage"),
	new Equipment("Breastplate","0","Medium,AC = 14 + Dex modifier (max 2)"),
	new Equipment("Half plate","0","Medium,AC = 15 + Dex modifier (max 2),Stealth Disadvantage"),
	new Equipment("Ring mail","0","Heavy,AC = 14,Stealth Disadvantage"),
	new Equipment("Chain mail","0","Heavy,AC = 16,Str 13,Stealth Disadvantage"),
	new Equipment("Splint","0","Heavy,AC = 17,Str 15,Stealth Disadvantage"),
	new Equipment("Plate","0","Heavy,AC = 18,Str 15,Stealth Disadvantage"),
	new Equipment("Shield","0","Shield,+2 AC"),
];

const spells = [
	new Spell("Acid Splash",0,1),
	new Spell("Chill Touch",0,1),
	new Spell("Dancing Lights",0,1),
	new Spell("Druidcraft",0,1),
	new Spell("Eldritch Blast",0,1),
	new Spell("Fire Bolt",0,1),
	new Spell("Guidance",0,1),
	new Spell("Light",0,1),
	new Spell("Mage Hand",0,1),
	new Spell("Mending",0,1),
	new Spell("Message",0,1),
	new Spell("Minor Illusion",0,1),
	new Spell("Poison Spray",0,1),
	new Spell("Prestidigitation",0,1),
	new Spell("Produce Flame",0,1),
	new Spell("Ray of Frost",0,1),
	new Spell("Resistance",0,1),
	new Spell("Sacred Flame",0,1),
	new Spell("Shillelagh",0,1),
	new Spell("Shocking Grasp",0,1),
	new Spell("Spare the Dying",0,1),
	new Spell("Thaumaturgy",0,1),
	new Spell("True Strike",0,1),
	new Spell("Vicious Mockery",0,1),
	new Spell("Alarm",1,1),
	new Spell("Animal Friendship",1,1),
	new Spell("Bane",1,1),
	new Spell("Bless",1,1),
	new Spell("Burning Hands",1,1),
	new Spell("Charm Person",1,1),
	new Spell("Color Spray",1,1),
	new Spell("Command",1,1),
	new Spell("Comprehend Languages",1,1),
	new Spell("Create or Destroy Water",1,1),
	new Spell("Cure Wounds",1,1),
	new Spell("Detect Evil and Good",1,1),
	new Spell("Detect Magic",1,1),
	new Spell("Detect Poison and Disease",1,1),
	new Spell("Disguise Self",1,1),
	new Spell("Divine Favor",1,1),
	new Spell("Entangle",1,1),
	new Spell("Expeditious Retreat",1,1),
	new Spell("Faerie Fire",1,1),
	new Spell("False Life",1,1),
	new Spell("Feather Fall",1,1),
	new Spell("Find Familiar",1,1),
	new Spell("Floating Disk",1,1),
	new Spell("Fog Cloud",1,1),
	new Spell("Goodberry",1,1),
	new Spell("Grease",1,1),
	new Spell("Guiding Bolt",1,1),
	new Spell("Healing Word",1,1),
	new Spell("Hellish Rebuke",1,1),
	new Spell("Heroism",1,1),
	new Spell("Hideous Laughter",1,1),
	new Spell("Hunter's Mark",1,1),
	new Spell("Identify",1,1),
	new Spell("Illusory Script",1,1),
	new Spell("Inflict Wounds",1,1),
	new Spell("Jump",1,1),
	new Spell("Longstrider",1,1),
	new Spell("Mage Armor",1,1),
	new Spell("Magic Missile",1,1),
	new Spell("Protection from Evil and Good",1,1),
	new Spell("Purify Food and Drink",1,1),
	new Spell("Sanctuary",1,1),
	new Spell("Shield",1,1),
	new Spell("Shield of Faith",1,1),
	new Spell("Silent Image",1,1),
	new Spell("Sleep",1,1),
	new Spell("Speak with Animals",1,1),
	new Spell("Thunderwave",1,1),
	new Spell("Unseen Servant",1,1),
	new Spell("Acid Arrow",2,3),
	new Spell("Aid",2,3),
	new Spell("Alter Self",2,3),
	new Spell("Animal Messenger",2,3),
	new Spell("Arcane Lock",2,3),
	new Spell("Arcanist's Magic Aura",2,3),
	new Spell("Augury",2,3),
	new Spell("Barkskin",2,3),
	new Spell("Blindness/Deafness",2,3),
	new Spell("Blur",2,3),
	new Spell("Branding Smite",2,3),
	new Spell("Calm Emotions",2,3),
	new Spell("Continual Flame",2,3),
	new Spell("Darkness",2,3),
	new Spell("Darkvision",2,3),
	new Spell("Detect Thoughts",2,3),
	new Spell("Enhance Ability",2,3),
	new Spell("Enlarge/Reduce",2,3),
	new Spell("Enthrall",2,3),
	new Spell("Find Steed",2,3),
	new Spell("Find Traps",2,3),
	new Spell("Flame Blade",2,3),
	new Spell("Flaming Sphere",2,3),
	new Spell("Gentle Repose",2,3),
	new Spell("Gust of Wind",2,3),
	new Spell("Heat Metal",2,3),
	new Spell("Hold Person",2,3),
	new Spell("Invisibility",2,3),
	new Spell("Knock",2,3),
	new Spell("Lesser Restoration",2,3),
	new Spell("Levitate",2,3),
	new Spell("Locate Animals or Plants",2,3),
	new Spell("Locate Object",2,3),
	new Spell("Magic Mouth",2,3),
	new Spell("Magic Weapon",2,3),
	new Spell("Mirror Image",2,3),
	new Spell("Misty Step",2,3),
	new Spell("Moonbeam",2,3),
	new Spell("Pass without Trace",2,3),
	new Spell("Prayer of Healing",2,3),
	new Spell("Protection from Poison",2,3),
	new Spell("Ray of Enfeeblement",2,3),
	new Spell("Rope Trick",2,3),
	new Spell("Scorching Ray",2,3),
	new Spell("See Invisibility",2,3),
	new Spell("Shatter",2,3),
	new Spell("Silence",2,3),
	new Spell("Spider Climb",2,3),
	new Spell("Spike Growth",2,3),
	new Spell("Spiritual Weapon",2,3),
	new Spell("Suggestion",2,3),
	new Spell("Warding Bond",2,3),
	new Spell("Web",2,3),
	new Spell("Zone of Truth",2,3),
	new Spell("Animate Dead",3,5),
	new Spell("Beacon of Hope",3,5),
	new Spell("Bestow Curse",3,5),
	new Spell("Blink",3,5),
	new Spell("Call Lightning",3,5),
	new Spell("Clairvoyance",3,5),
	new Spell("Conjure Animals",3,5),
	new Spell("Counterspell",3,5),
	new Spell("Create Food and Water",3,5),
	new Spell("Daylight",3,5),
	new Spell("Dispel Magic",3,5),
	new Spell("Fear",3,5),
	new Spell("Fireball",3,5),
	new Spell("Fly",3,5),
	new Spell("Gaseous Form",3,5),
	new Spell("Glyph of Warding",3,5),
	new Spell("Haste",3,5),
	new Spell("Hypnotic Pattern",3,5),
	new Spell("Lightning Bolt",3,5),
	new Spell("Magic Circle",3,5),
	new Spell("Major Image",3,5),
	new Spell("Mass Healing Word",3,5),
	new Spell("Meld into Stone",3,5),
	new Spell("Nondetection",3,5),
	new Spell("Phantom Steed",3,5),
	new Spell("Plant Growth",3,5),
	new Spell("Protection from Energy",3,5),
	new Spell("Remove Curse",3,5),
	new Spell("Revivify",3,5),
	new Spell("Sending",3,5),
	new Spell("Sleet Storm",3,5),
	new Spell("Slow",3,5),
	new Spell("Speak with Dead",3,5),
	new Spell("Speak with Plants",3,5),
	new Spell("Spirit Guardians",3,5),
	new Spell("Stinking Cloud",3,5),
	new Spell("Tiny Hut",3,5),
	new Spell("Tongues",3,5),
	new Spell("Vampiric Touch",3,5),
	new Spell("Water Breathing",3,5),
	new Spell("Water Walk",3,5),
	new Spell("Wind Wall",3,5),
	new Spell("Arcane Eye",4,7),
	new Spell("Banishment",4,7),
	new Spell("Black Tentacles",4,7),
	new Spell("Blight",4,7),
	new Spell("Compulsion",4,7),
	new Spell("Confusion",4,7),
	new Spell("Conjure Minor Elementals",4,7),
	new Spell("Conjure Woodland Beings",4,7),
	new Spell("Control Water",4,7),
	new Spell("Death Ward",4,7),
	new Spell("Dimension Door",4,7),
	new Spell("Divination",4,7),
	new Spell("Dominate Beast",4,7),
	new Spell("Fabricate",4,7),
	new Spell("Faithful Hound",4,7),
	new Spell("Fire Shield",4,7),
	new Spell("Freedom of Movement",4,7),
	new Spell("Giant Insect",4,7),
	new Spell("Greater Invisibility",4,7),
	new Spell("Guardian of Faith",4,7),
	new Spell("Hallucinatory Terrain",4,7),
	new Spell("Ice Storm",4,7),
	new Spell("Locate Creature",4,7),
	new Spell("Phantasmal Killer",4,7),
	new Spell("Polymorph",4,7),
	new Spell("Private Sanctum",4,7),
	new Spell("Resilient Sphere",4,7),
	new Spell("Secret Chest",4,7),
	new Spell("Stone Shape",4,7),
	new Spell("Stoneskin",4,7),
	new Spell("Wall of Fire",4,7),
	new Spell("Animate Objects",5,9),
	new Spell("Antilife Shell",5,9),
	new Spell("Arcane Hand",5,9),
	new Spell("Awaken",5,9),
	new Spell("Cloudkill",5,9),
	new Spell("Commune",5,9),
	new Spell("Commune with Nature",5,9),
	new Spell("Cone of Cold",5,9),
	new Spell("Conjure Elemental",5,9),
	new Spell("Contact Other Plane",5,9),
	new Spell("Contagion",5,9),
	new Spell("Creation",5,9),
	new Spell("Dispel Evil and Good",5,9),
	new Spell("Dominate Person",5,9),
	new Spell("Dream",5,9),
	new Spell("Flame Strike",5,9),
	new Spell("Geas",5,9),
	new Spell("Greater Restoration",5,9),
	new Spell("Hallow",5,9),
	new Spell("Hold Monster",5,9),
	new Spell("Insect Plague",5,9),
	new Spell("Legend Lore",5,9),
	new Spell("Mass Cure Wounds",5,9),
	new Spell("Mislead",5,9),
	new Spell("Modify Memory",5,9),
	new Spell("Passwall",5,9),
	new Spell("Planar Binding",5,9),
	new Spell("Raise Dead",5,9),
	new Spell("Reincarnate",5,9),
	new Spell("Scrying",5,9),
	new Spell("Seeming",5,9),
	new Spell("Telekinesis",5,9),
	new Spell("Telepathic Bond",5,9),
	new Spell("Teleportation Circle",5,9),
	new Spell("Tree Stride",5,9),
	new Spell("Wall of Force",5,9),
	new Spell("Wall of Stone",5,9),
	new Spell("Blade Barrier",6,11),
	new Spell("Chain Lightning",6,11),
	new Spell("Circle of Death",6,11),
	new Spell("Conjure Fey",6,11),
	new Spell("Contingency",6,11),
	new Spell("Create Undead",6,11),
	new Spell("Disintegrate",6,11),
	new Spell("Eyebite",6,11),
	new Spell("Find the Path",6,11),
	new Spell("Flesh to Stone",6,11),
	new Spell("Forbiddance",6,11),
	new Spell("Freezing Sphere",6,11),
	new Spell("Globe of Invulnerability",6,11),
	new Spell("Guards and Wards",6,11),
	new Spell("Harm",6,11),
	new Spell("Heal",6,11),
	new Spell("Heroes' Feast",6,11),
	new Spell("Instant Summons",6,11),
	new Spell("Irresistible Dance",6,11),
	new Spell("Magic Jar",6,11),
	new Spell("Mass Suggestion",6,11),
	new Spell("Move Earth",6,11),
	new Spell("Planar Ally",6,11),
	new Spell("Programmed Illusion",6,11),
	new Spell("Sunbeam",6,11),
	new Spell("Transport via Plants",6,11),
	new Spell("True Seeing",6,11),
	new Spell("Wall of Ice",6,11),
	new Spell("Wall of Thorns",6,11),
	new Spell("Wind Walk",6,11),
	new Spell("Word of Recall",6,11),
	new Spell("Arcane Sword",7,13),
	new Spell("Conjure Celestial",7,13),
	new Spell("Delayed Blast Fireball",7,13),
	new Spell("Divine Word",7,13),
	new Spell("Etherealness",7,13),
	new Spell("Finger of Death",7,13),
	new Spell("Fire Storm",7,13),
	new Spell("Forcecage",7,13),
	new Spell("Magnificent Mansion",7,13),
	new Spell("Mirage Arcane",7,13),
	new Spell("Plane Shift",7,13),
	new Spell("Prismatic Spray",7,13),
	new Spell("Project Image",7,13),
	new Spell("Regenerate",7,13),
	new Spell("Resurrection",7,13),
	new Spell("Reverse Gravity",7,13),
	new Spell("Sequester",7,13),
	new Spell("Simulacrum",7,13),
	new Spell("Symbol",7,13),
	new Spell("Teleport",7,13),
	new Spell("Animal Shapes",8,15),
	new Spell("Antimagic Field",8,15),
	new Spell("Antipathy/Sympathy",8,15),
	new Spell("Clone",8,15),
	new Spell("Control Weather",8,15),
	new Spell("Demiplane",8,15),
	new Spell("Dominate Monster",8,15),
	new Spell("Earthquake",8,15),
	new Spell("Feeblemind",8,15),
	new Spell("Glibness",8,15),
	new Spell("Holy Aura",8,15),
	new Spell("Incendiary Cloud",8,15),
	new Spell("Maze",8,15),
	new Spell("Mind Blank",8,15),
	new Spell("Power Word Stun",8,15),
	new Spell("Sunburst",8,15),
	new Spell("Astral Projection",9,17),
	new Spell("Foresight",9,17),
	new Spell("Gate",9,17),
	new Spell("Imprisonment",9,17),
	new Spell("Mass Heal",9,17),
	new Spell("Meteor Swarm",9,17),
	new Spell("Power Word Kill",9,17),
	new Spell("Prismatic Wall",9,17),
	new Spell("Shapechange",9,17),
	new Spell("Storm of Vengeance",9,17),
	new Spell("Time Stop",9,17),
	new Spell("True Polymorph",9,17),
	new Spell("True Resurrection",9,17),
	new Spell("Weird",9,17),
	new Spell("Wish",9,17),

]

